//CREO LA MIA MIDDLEWARE CON UN ARROW FUCNTION
const clientError = (req, res, next) => { //INSERISCO I PARAMETRI NECESSARI PER CREARLA E PER GESTIRMI L'ERRORE LATO SERVER
    
    res.status(404) //IMPOSTO LO STATO

    res.json({ //NON HO BISOGNO DI NEXT (NON HO NESSUNO A CUI PASSARE 'LA PALLA') MA RESTITUISCO DIRETTAMENTE UNA RISPOSTA (PER EVITARE IL LOOP) IN FORMATO JSON 
        error: 'Not Found',
        status: 404
    })
}

module.exports = clientError //ESPORTO IL TUTTO